import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppSidebar from "@/components/AppSidebar";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "@/components/provider/ThemeProvider";
import { SidebarProvider } from "@/components/ui/sidebar";
import { cookies } from "next/headers";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Faundy",
  description: "Generated by FaundyTeam",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies()
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true"
 
  return (
    <html lang="en" suppressHydrationWarning >
       <head>
        {/* Light Mode */}
        <link
          rel="icon"
          href="/FaundyDark.svg"
          type="image/svg+xml"
          media="(prefers-color-scheme: light)"
          sizes="any"
        />
        {/* Dark Mode */}
        <link
          rel="icon"
          href="/Faundy.svg"
          type="image/svg+xml"
          media="(prefers-color-scheme: dark)"
        />
        {/* Fallback */}
        <link
          rel="icon"
          href="/Faundy.svg"
          type="image/svg+xml"
        />
      </head> 
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex`}
      >
        
        <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
        >

       <SidebarProvider defaultOpen={defaultOpen}>
        
        <AppSidebar/>
        
        <main className="w-full">
         <Navbar/>

         <div className="px-4">{children}</div>

        </main>

        </SidebarProvider>

        </ThemeProvider>
       
      
      </body>
    </html>
  );
}
